# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(email:"user1@domain.com", password: "qwerqwer", password_confirmation:"qwerqwer")

User.create(email: "user2@domain.com", password: "qwerqwer", password_confirmation: "qwerqwer")

Escapade.create(title: "Thailand", image: "http://www.findatour.co/UserImage/hassani%20seo/thailand%20tour.jpg", start_date: "2016-01-01", end_date: "2016-05-01", description: "Truffaut trust fund brooklyn godard lo-fi hella, flexitarian stumptown offal food truck taxidermy jean shorts. Microdosing try-hard green juice aesthetic dreamcatcher. Pop-up quinoa hammock fap, banh mi shoreditch health goth small batch tattooed mustache hashtag selvage YOLO chambray letterpress. IPhone cliche heirloom, stumptown bicycle rights celiac green juice intelligentsia deep v VHS tote bag pork belly scenester yuccie mixtape. Shoreditch taxidermy bespoke franzen etsy offal vice. Put a bird on it cray kogi schlitz, bitters PBR&B polaroid tilde vinyl twee poutine DIY XOXO small batch. Cray forage wayfarers, occupy yuccie pitchfork pop-up vinyl swag pickled scenester tacos blog put a bird on it.", user_id: 1)

Escapade.create(title: "Norwegian Adventure", image: "http://www.infohostels.com/immagini/news/2254.jpg", start_date: "02-01-2016", end_date: "03-01-2016", description: "Butcher kinfolk craft beer tumblr seitan post-ironic. Tacos microdosing squid pour-over four loko, hella portland cronut humblebrag authentic kombucha migas. +1 XOXO YOLO banjo, green juice roof party umami. Butcher sustainable listicle meh, pabst leggings fap schlitz dreamcatcher mlkshk. Gastropub authentic chartreuse chicharrones, sriracha williamsburg salvia keytar 3 wolf moon brunch marfa mixtape kitsch fingerstache irony. Truffaut trust fund brooklyn godard lo-fi hella, flexitarian stumptown offal food truck taxidermy jean shorts. Microdosing try-hard green juice aesthetic dreamcatcher. Pop-up quinoa hammock fap, banh mi shoreditch health goth small batch tattooed mustache hashtag selvage YOLO chambray letterpress. IPhone cliche heirloom, stumptown bicycle rights celiac green juice intelligentsia deep v VHS tote bag pork belly scenester yuccie mixtape. Shoreditch taxidermy bespoke franzen etsy offal vice. Put a bird on it cray kogi schlitz, bitters PBR&B polaroid tilde vinyl twee poutine DIY XOXO small batch. Cray forage wayfarers, occupy yuccie pitchfork pop-up vinyl swag pickled scenester tacos blog put a bird on it.", user_id: 1)

Escapade.create(title: "Trapeze Class", image: "http://washingtondc.trapezeschool.com/community/TSNYgallery/images/sunsetCatch-CH.jpg", start_date: "2015-12-01", end_date:"2015-12-31", description: "Intelligentsia distillery VHS sriracha tattooed, dreamcatcher echo park DIY next level pour-over normcore gentrify. Celiac PBR&B tacos seitan yr. Wayfarers kitsch health goth, tattooed gluten-free sustainable farm-to-table tote bag +1 90's art party. Tacos ramps farm-to-table selvage pickled XOXO williamsburg cred. Sartorial literally freegan bushwick chia roof party, gentrify sustainable chicharrones brooklyn. Salvia viral kombucha neutra, skateboard twee craft beer street art blue bottle. Health goth cred echo park pitchfork, chillwave cliche fingerstache lomo bespoke.", user_id: 1)

Escapade.create(title: "Wonder Exhibit", image: "http://media.npr.org/assets/img/2015/11/12/grade_middlefork_custom-a23c871f26659f6ab1a6ff2891a18ec445f47416-s800-c85.jpg", start_date: "2015-11-16", end_date: "2015-12-19", description: "In the Renwick's newly renovated gallery in Washington, D.C., nine artists were each given free rein over a space to create inspiring installations. Tara Donovan used hundreds of thousands of index cards to create a mountain range. Gabriel Dawe made a rainbow out of some 60 miles of colored thread. Patrick Dougherty turned sticks into giant, swirling nests.", user_id: 2)

Response.create(comment: "This sounds awesome!", start_date: "2015-01-01", end_date: "2015-01-31", escapade_id: 1)
