# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Escapade.create(title: "Thailand", image: "http://www.findatour.co/UserImage/hassani%20seo/thailand%20tour.jpg", start_date: "2016-01-01", end_date: "2016-05-01", description: "Truffaut trust fund brooklyn godard lo-fi hella, flexitarian stumptown offal food truck taxidermy jean shorts. Microdosing try-hard green juice aesthetic dreamcatcher. Pop-up quinoa hammock fap, banh mi shoreditch health goth small batch tattooed mustache hashtag selvage YOLO chambray letterpress. IPhone cliche heirloom, stumptown bicycle rights celiac green juice intelligentsia deep v VHS tote bag pork belly scenester yuccie mixtape. Shoreditch taxidermy bespoke franzen etsy offal vice. Put a bird on it cray kogi schlitz, bitters PBR&B polaroid tilde vinyl twee poutine DIY XOXO small batch. Cray forage wayfarers, occupy yuccie pitchfork pop-up vinyl swag pickled scenester tacos blog put a bird on it.")

Escapade.create(title: "Norwegian Adventure", image: "http://www.infohostels.com/immagini/news/2254.jpg", start_date: "02-01-2016", end_date: "03-01-2016", description: "Butcher kinfolk craft beer tumblr seitan post-ironic. Tacos microdosing squid pour-over four loko, hella portland cronut humblebrag authentic kombucha migas. +1 XOXO YOLO banjo, green juice roof party umami. Butcher sustainable listicle meh, pabst leggings fap schlitz dreamcatcher mlkshk. Gastropub authentic chartreuse chicharrones, sriracha williamsburg salvia keytar 3 wolf moon brunch marfa mixtape kitsch fingerstache irony. Truffaut trust fund brooklyn godard lo-fi hella, flexitarian stumptown offal food truck taxidermy jean shorts. Microdosing try-hard green juice aesthetic dreamcatcher. Pop-up quinoa hammock fap, banh mi shoreditch health goth small batch tattooed mustache hashtag selvage YOLO chambray letterpress. IPhone cliche heirloom, stumptown bicycle rights celiac green juice intelligentsia deep v VHS tote bag pork belly scenester yuccie mixtape. Shoreditch taxidermy bespoke franzen etsy offal vice. Put a bird on it cray kogi schlitz, bitters PBR&B polaroid tilde vinyl twee poutine DIY XOXO small batch. Cray forage wayfarers, occupy yuccie pitchfork pop-up vinyl swag pickled scenester tacos blog put a bird on it.")
